name: shell commands
on: [push]

jobs:
  run-shell-command:

    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Amol, how are you"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Checkout code via v1
        uses: actions/checkout@v1
      - name: contents on v1 chckout  
        run: |
            ls
            pwd
     
      - name: Checkout code via v2
        uses: actions/checkout@v2
      - name: contents on v2 chckout
        run: |
          ls
          pwd
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory using powershell
        run: Get-Location
      - name: Directory using bash
        run: pwd
        shell: bash
        
