name: shell commands
on: [push]

jobs:
  run-shell-command:
    name: choosing agent
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Amol"
      - name: multiline script
        run: |
          node -v
          npm -v
